### ISSUE TITLE
JIDs must be split on the resourcepart first

### ISSUE THREAD

**Issue by SamWhited** [FluuxIO/go-xmpp#1]
The JID class needs to split on the resourcepart first and be more careful about how it's splitting. Eg. trying to parse the following valid JID will cause a panic: `test@domain.com/resource@moreresource/stillmoreresourcepart`

Disclaimer: Shameless self promotion follows. Feel free to steal code from my implementation [here](https://bitbucket.org/mellium/xmpp/src/150780b88cc2cdeeb486eaf759f74228254daffa/jid/?at=master). I'd love to collaborate and reduce code duplication on some of this. I also have an issue at golang/go#13797 to add JIDs into the x/net package. No idea if that will be accepted or not though.

_EDIT:_ I just noticed that there's a test to make sure that `test@domain.com/test/test` is invalid, but this is a perfectly valid JID. Not sure if this was deliberate or not.

**Comment by mremond** [comment]
Thanks, I will fix this. Yes, the test was deliberate, but indeed, that split code can be improved.
