### ISSUE TITLE
Support registering new types into IQ payload type registry

### ISSUE THREAD

**Issue by ivucica** [FluuxIO/go-xmpp#10]
IQ code has a pretty slick way of registering a struct into which an IQ payload should be unmarshaled using `reflect` package's `TypeOf`.

Unfortunately, all types are hardcoded.

It would be a nice way to send custom, currently unsupported payloads (e.g. User Activity for PEP) if the library would allow registering new types into the type registry.

Would it make sense to create such a public API?

**Comment by mremond** [comment]
I am currently working on that and you now have a registry that you should be able to reuse to add your own custom module.
I still do not like the fact that it is a package-level global variable, so I will try to improve it soon to make the API exist at the XMPP Client level. It will be cleaner.

**Comment by mremond** [comment]
I am closing this as I exposed the TypeRegistry and documented how to create a custom extension in your own client code.
This is documented in this commit: https://github.com/FluuxIO/go-xmpp/commit/e3c0747cbb3463114aaac77d4915c9f72b5c2942
