### ISSUE TITLE
Allow custom route matchers

### ISSUE THREAD

**Issue by wichert** [FluuxIO/go-xmpp#102]
When implementing a component handler I find myself needing to route based on the payload of an IQ message. Currently this requires you to register a generic IQ namespace handler, and do your own routing in that. Something like:

```go
router.NewRoute().IQNamespaces(NSMyProtocol).StanzaType("get").HandlerFunc(func (s xmpp.Sender, p stanza.Packet) {
    iq, ok := p.(xmpp.IQ)
    if !ok {
        return
    }

    switch payload := iq.Payload.(type) {
    case FooPayload:
        handleFoo(s, p)
    case BarPayload:
        handleBar(s, p)
    }
})
```

If would be very convenient if addMatcher was exposed so you could do something like this:

```go

type myProtocolMatcher string

func (n myProtocolMatcher) Match(p stanza.Packet, match *RouteMatch) bool {
    iq, ok := p.(xmpp.IQ)
    if !ok {
        return false
    }
    // This assumes we have an iq.Payload extension registered with a struct type that
    // adds a Local() method. It would be very convenient if IQPayload already has that.
    return iq.Payload.Namespace() == NSMyProtocol && iq.Payload != nil && iq.Payload.Local() == n
}

router.NewRoute().AddMatcher(myProtocolMatcher("foo")).HandlerFunc(…)

```

**Comment by wichert** [comment]
Would you accept a PR that exposes addMatcher by renaming it to AddMatcher ?

**Comment by mremond** [comment]
@wichert Yes, please go ahead :) If you rename, check the example as well please :)

**Comment by wichert** [comment]
Done! As far as I could see no examples needed to be updated.

**Comment by mremond** [comment]
Many thanks !

**Comment by wichert** [comment]
@mremond Would it be possible to tag a release with this change?

**Comment by mremond** [comment]
@wichert of course, good idea.
I will do that early next week.

**Comment by mremond** [comment]
Done, I tagged v0.1.2.
