### ISSUE TITLE
Component's .Send() incorrectly uses fmt.Fprintf() to send to a connection

### ISSUE THREAD

**Issue by ivucica** [FluuxIO/go-xmpp#103]
In `component.Send()` in line 157, `fmt.Fprintf()` uses the marshaled data as a format string:

https://github.com/FluuxIO/go-xmpp/blob/3de99e0e0e6582486ad052edcc41bbce12205c5c/component.go#L145-L161

This means that if there is anything that looks like a format string (`%s`, `%d`, ...) in the marshaled data, such as encoded URLs, one will something like the following sent over the connection:

```
<put url="http://localhost/something/tr%!C(MISSING)3%!A(MISSING)8s%!c(MISSING)ool.jpg">
```

A trivial solution is to use `fmt.Fprintf(conn, "%s", string(data))`.

A better solution is to send `[]byte` onto the connection directly, using `conn.Write(data)`.

An alternative solution is to serialize directly onto the connection using an `xml.Encoder` tied to `conn`, and then invoking `enc.Encode(packet)`.

**Comment by remicorniere** [comment]
Fixed in  #135
