### ISSUE TITLE
StreamManager.Close() -> segfault

### ISSUE THREAD

**Issue by Kroev** [FluuxIO/go-xmpp#107]
Hello,

There is an issue with calling `StreamManager.Close()` causing a segfault in certain situations:
```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x785260]

goroutine 1 [running]:
gosrc.io/xmpp.(*Client).Disconnect(0xc4200a9860)
        /go/src/gosrc.io/xmpp/client.go:192 +0x50
gosrc.io/xmpp.(*StreamManager).Stop(0xc42014c630)
        /go/src/gosrc.io/xmpp/stream_manager.go:106 +0x52
[...]
```

As far as I can tell this happens 
1) if the client is not yet connected
2) if the connection went down (lost tcp connection and then calling SM.Close() )

I underestand that these are situations where closing the SM should not be necessary but there is no way to tell.

I am thinking of two different approaches to fix this:
* make client object accessable from the sm, so something like `sm.Client.CurrentState` is possible
* as I understand why you would not want to let people fiddle with the client in a SM, a getter for the client state: `sm.CurrentState()` or similar

This would enable me to tell wehther I need to close the SM or not.

Kroev

**Comment by mremond** [comment]
I think a better approach would be to guard against the crash and let the client call Close at any time, no matter what the state is.

**Comment by mremond** [comment]
It should be fixed by this commit: https://github.com/FluuxIO/go-xmpp/commit/8794ea6ed8e17c357c7398adef3e84838b2f9b87

Could you please reopen the issue if this is not the case?

Thanks for the report!
