### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by wichert** [FluuxIO/go-xmpp#112]
Is there any interest in adding support for XMPP over websockets? I may be willing to take a tab at implementing that.

**Comment by mremond** [comment]
Hello, I think this could be interesting, but maybe not very high priority.
Websocket is something that you would use from a webclient. I am not sure this is something I would use for a Go client so running as a native client with access to full socket implementation.

What do you plan to use it for ?

**Comment by wichert** [comment]
I need to talk to an XMPP server that is only exposed via a websocket; people are very hesitant to also expose the XMPP port directly. From a security point of view I can understand it: for websockets you can easily leverage existing SSL provisioning and nginx proxy systems with all their security features.

**Comment by mremond** [comment]
ok, that's strange because I have never seen this case with only Websocket being allowed, as using websocket outside of the browser is (or used to be) a bit painful.

**Comment by wichert** [comment]
In this case all clients have been either browsers or Electron or React Native based apps, using a shared codebase, so it isn't very surprising for this instance.
