### ISSUE TITLE
Problem with unescaped character %

### ISSUE THREAD

**Issue by mdosch** [FluuxIO/go-xmpp#113]
I have a little bot which was sending me a message `https://da.wikipedia.org/wiki/J%C3%A6vnd%C3%B8gn 🔭` as `https://da.wikipedia.org/wiki/J%!C(MISSING)3%!A(MISSING)6vnd%!C(MISSING)3%!B(MISSING)8gn`.

@SamWhited figured out that it probably happens due to fprintf in the library which considered % a control character. I fixed this quick and dirty by replacing % by %% before sending but you should consider to properly escape messages before using fprintf.

But even with that little workaround there is still a problem as `Septemberjævndøgn ⌘ https://da.wikipedia.org/wiki/J%C3%A6vnd%C3%B8gn 🔭` turns to `Septemberjvndgn  https://da.wikipedia.org/wiki/J%C3%A6vnd%C3%B8gn`.

**Comment by mremond** [comment]
Thanks for reporting this, we will have a look.

**Comment by mdosch** [comment]
Thanks. 😃

Am September 27, 2019 2:32:56 PM UTC schrieb "Mickaël Rémond" <notifications@github.com>:
>Closed #113 via #114.
