### ISSUE TITLE
IQ handler gets not invoked

### ISSUE THREAD

**Issue by mdosch** [FluuxIO/go-xmpp#118]
https://github.com/FluuxIO/go-xmpp/blob/2781563ea7698168d48f87295adf27baf8b6636c/_examples/xmpp_jukebox/xmpp_jukebox.go#L49

I am irritated as my IQ handler never gets called. I already tried changing `Packet("message").` to `Packet("iq").` but it didn't change the behavior.

Maybe you can check if this example is correct.

**Comment by mremond** [comment]
Hi, do you have some more context info or code to share ?
Does the issue happen all the time, or after a reconnect ? Maybe the context the lost somehow.

**Comment by mdosch** [comment]
Sorry, I'm quite busy, I'll dig into it once I find time again.

Am October 11, 2019 1:53:31 PM UTC schrieb "Mickaël Rémond" <notifications@github.com>:
>Hi, do you have some more context info or code to share ?
>Does the issue happen all the time, or after a reconnect ? Maybe the
>context the lost somehow.

**Comment by mdosch** [comment]
Hi,

finally i found time to check again. I don't know if you changed 
something regarding this but it is working now. So this issue can be 
closed.

Thanks for this lib.
