### ISSUE TITLE
go get fluux.io/xmpp failed

### ISSUE THREAD

**Issue by shrhdk** [FluuxIO/go-xmpp#12]
Server certificate is expired.

```
$ go get fluux.io/xmpp
package fluux.io/xmpp: unrecognized import path "fluux.io/xmpp" (https fetch: Get https://fluux.io/xmpp?go-get=1: x509: certificate has expired or is not yet valid)
```

**Comment by shrhdk** [comment]
Sometimes success and sometimes fail. I think that some instance has correct certificate and Some instance has incorrect certificate.

**Comment by mremond** [comment]
Sorry about the trouble, it should be fixed now.

**Comment by shrhdk** [comment]
Thank you :+1:

**Comment by mremond** [comment]
For your information, to prevent further failure, I move the project to gosrc.io/xmpp

I hope this helps :)
