### ISSUE TITLE
Implementation of stanza acknowledgement (XEP-0198)

### ISSUE THREAD

**Issue by logicwonder** [FluuxIO/go-xmpp#127]
- Component must be able to enable stanza acknowledgement along with stream management
- Provide option to request for stanza acknowledgement when sending message to server
- Provide a handler to listen to stanza acknowledgements received from server

**Comment by logicwonder** [comment]
This enables the component to resend a message if no acknowledgement is received from server after a timeout.

**Comment by remicorniere** [comment]
New in v0.5.0
