### ISSUE TITLE
PubSub stanza should be more generic

### ISSUE THREAD

**Issue by wichert** [FluuxIO/go-xmpp#131]
More specifically: stanza.Item is defined like this:

```go
type Item struct {
        XMLName xml.Name `xml:"item"`
        Id      string   `xml:"id,attr,omitempty"`
        Tune    *Tune
        Mood    *Mood
}
```

Which is not very useful if you build anything other than the jukebox example :). 

Should this use a similar approach as used for IQ packets? Or perhaps `Publish` should use `Node` as type for its item element?

**Comment by remicorniere** [comment]
I made a first version of this, see #142 .  
I tried adding helper functions for many cases that were described in [XEP-0060](https://xmpp.org/extensions/xep-0060.html).   
I might change the "generic" pubsub schema though to reflect <xs:choice> tags in the 17.1 http://jabber.org/protocol/pubsub at [XEP-0060-Schemas](https://xmpp.org/extensions/xep-0060.html#schemas) like I did for the http://jabber.org/protocol/pubsub#owner namespace for instance.
