### ISSUE TITLE
Add support for roster IQ stanzas

### ISSUE THREAD

**Issue by remicorniere** [FluuxIO/go-xmpp#137]

**Comment by wichert** [comment]
I implemented those recently, see https://gist.github.com/wichert/dfd664d9077980c71b7e2064e5e7bdfe

Shall I do a quick PR with those files?

**Comment by remicorniere** [comment]
Thanks ! 
I have implemented this too, with a bit more features. I'll take your test though, if you don't mind !

**Comment by wichert** [comment]
I'm guessing there are a dozen implementations of this 😀  Feel free to take any parts you want.

**Comment by remicorniere** [comment]
Thanks ! :)
