### ISSUE TITLE
Prosody & "echo" demo: not receiving any messages

### ISSUE THREAD

**Issue by yojoe** [FluuxIO/go-xmpp#160]
I'm a new user of `go-xmpp` and playing with the examples right now. I'm using Prosody as the XMPP server to talk with. I can successfully authenticate but no messages are delivered/routed to the `echo client`. After the session is initialized the `StreamLogger` stays silent and never logs anything else, no messages, no IQs, pings, ...).

When I modify the example code I can even send messages from the `echo client` which are delivered successfully but still, no stanzas are ever received. Looking into the discussion of https://github.com/FluuxIO/go-xmpp/issues/9 I implemented a `postConnect` function to manually set the presence (which the echo demo client never did), but that doesn't help. Prosody doesn't deliver any messages to the `echo demo client`.

**Comment by yojoe** [comment]
The issue seems to be in the use of `StreamManager` (which seems to have a bug) and not a Prosody specific problem. `StreamManager.Run()` calls the lowercase `connect()` instead of the uppercase `Connect()`, hence `c.recv()` is never called when `StreamManager` is used:

https://github.com/FluuxIO/go-xmpp/blob/1e92089f963132dada5f78135571f11027242664/stream_manager.go#L99

https://github.com/FluuxIO/go-xmpp/blob/64e54134dfab14046a74dc07f7b91a9c6327d66a/client.go#L233-L237

**Comment by remicorniere** [comment]
Hello @yojoe and thank you for reporting the issue ! 
I tried making a fix for this, that you can find in this pull request : #161 . Would you mind trying it to see if it fixes the issue on your side ?
Thanks again !

**Comment by yojoe** [comment]
Yes, it fixes the issue.

However, I noticed that `StreamManager` and `Client` might have another sleeping bug:

https://github.com/FluuxIO/go-xmpp/blob/ef6de6000a0d333c577b7c1292fc848d2ba12194/stream_manager.go#L96

What is `sm.SetHandler(handler)` supposed to achieve? It just sets a field in `Client` which is never used:

https://github.com/FluuxIO/go-xmpp/blob/ef6de6000a0d333c577b7c1292fc848d2ba12194/client.go#L305-L307

In fact, `c.Handler` isn't even defined in the struct definition:
https://github.com/FluuxIO/go-xmpp/blob/ef6de6000a0d333c577b7c1292fc848d2ba12194/client.go#L126-L146

And I can't find any other code in the project which ever accesses/uses `c.Handler`. Therefore I wonder if the lines defining the handler in `StreamManager` will ever be used:
https://github.com/FluuxIO/go-xmpp/blob/ef6de6000a0d333c577b7c1292fc848d2ba12194/stream_manager.go#L77-L96

**Comment by yojoe** [comment]
Could it be that line 306
https://github.com/FluuxIO/go-xmpp/blob/ef6de6000a0d333c577b7c1292fc848d2ba12194/client.go#L305-L307
should instead be
```
c.EventManager.Handler = handler
```

**Comment by remicorniere** [comment]
No problem @yojoe !
This is called "type embedding". You can find more information on it here for instance :
https://www.ardanlabs.com/blog/2014/05/methods-interfaces-and-embedded-types.html

The handler here is used to trigger an action when the client state is changed. If you take a look at "stream_manager.go", inside the "Run()" method, we declare a specific handler that uses a switch case on the client state, and triggers an appropriate action.  

If you check the client.go file, you'll see currently three methods (updateState, disconnected and streamError) that trigger the handler, and that are called when the client state changes.

Stream_manager is basically an "example implementation" for this handler, but you could use the client any other way if you wanted to trigger different actions for different states changes. This is what the handler is for.

If you're ok with my correction and don't have any more questions I'll close this issue.  
Thanks again for contributing !

**Comment by yojoe** [comment]
Thanks for the explanation! Yes, please close it.

**Comment by jacksgt** [comment]
Hello there and thanks for resolving this issue so quickly!

After trying to figure out for some time why the basic echo example is not working, I stumbled onto this issue.
I just wanted to confirm that this issue is also present with ejabberd.

Could you please make a new patch release (0.5.1) since this issue breaks really basic functionality?
(In my case I just `go get gosrc.io/xmpp`, which by default chooses the latest available release.)

Many thanks!

**Comment by remicorniere** [comment]
Hello @jacksgt !
That seems reasonable. It's done !
