### ISSUE TITLE
godocs are down

### ISSUE THREAD

**Issue by philipwilsonchang** [FluuxIO/go-xmpp#19]
The godocs have been down for a handful of weeks now:

![image](https://user-images.githubusercontent.com/17068755/54944004-edd4f500-4f08-11e9-8d7c-2d63c569dcdc.png)

Any ideas on what is causing it/how to fix it?

**Comment by mremond** [comment]
@philipwilsonchang It seems to be working right now. Please, let us know if you see that it is not working as expected.

Thanks!
