### ISSUE TITLE
XEP-0184: Message Delivery Receipts

### ISSUE THREAD

**Issue by genofire** [FluuxIO/go-xmpp#24]
Any Idea how to support it?
https://xmpp.org/extensions/xep-0184.html

Maybe by adding in `Message`:
```golang
	// Any hasn't matched element
	Other []XMLElement `xml:",any"`
```

**Comment by mremond** [comment]
Hi,

I wrote a quick and dirty draft of how I would do it: https://github.com/FluuxIO/go-xmpp/tree/msg_extension

I would probably need to refactor that and move some code around, likely try to merge that with the registry for IQPayload and possibly make the registry less hardcoded and more extensible by different module.

So, work in progress, but you should get the idea :)

**Comment by mremond** [comment]
It should be fixed by https://github.com/FluuxIO/go-xmpp/pull/27
