### ISSUE TITLE
TLS domain from JID is wrong

### ISSUE THREAD

**Issue by jonni-larjomaa** [FluuxIO/go-xmpp#3]
When creating tls connection the domain should be the connection address not JID domain part. there might be situation where connection is made to xmpp.example.com and jids are <user>@example.com. this causes the tls fail.

**Comment by mremond** [comment]
Thanks, for the report. I think it makes sense.

**Comment by mremond** [comment]
The current behaviour is actually correct. The server should be configured with a certificate for the domain not for the server hostname.

The client should check that:
1. the domain of the server is the same as the one from its jid.
2. use that domain to check against the certificate. The domain part of the JID must be in either commonName (subject) or in SAN of the certificate.

So, you should fix your server configuration.
