### ISSUE TITLE
Make client_manager able to manage any connection

### ISSUE THREAD

**Issue by mremond** [FluuxIO/go-xmpp#38]
Client manager should be able to handle reconnect and exponential back-off on both client connection and component connection.

**Comment by mremond** [comment]
I started working on it in the branch: https://github.com/FluuxIO/go-xmpp/tree/StreamManager

**Comment by mremond** [comment]
@genofire I have make the component be able to be managed by a "StreamManager".

Please, check the updated example: https://github.com/FluuxIO/go-xmpp/blob/master/_examples/xmpp_component/xmpp_component.go

I hope this helps 😄

**Comment by genofire** [comment]
Thank you to announce the change to m :+1:
