### ISSUE TITLE
MUC support

### ISSUE THREAD

**Issue by genofire** [FluuxIO/go-xmpp#67]
I found my old code again ... [yaja](https://dev.sum7.eu/genofire/yaja/)- most of the handling is a little bit trash.

But the library of structs is still not bad (here: [xmpp](https://dev.sum7.eu/genofire/yaja/tree/master/xmpp))

The parsing is really easy: https://dev.sum7.eu/genofire/yaja/blob/master/client/comm.go#L9-37.

Another nice feature is, that it is not necessary to iterate over all `Message.Extensions` we could just make a `if PresenceClient.MUC !=nil` because `omitempty` pointer are filled with `nil` if the values for this `structs` are not given.

atm i miss somethings to replace other libraries in related project:
- muc support
- obb (to publish image urls as http_upload)
- html body

**Comment by mremond** [comment]
Thanks for the pointer, I will have a look.
Let's try to make it possible for you to use the same underlying client for all your code base :)

**Comment by genofire** [comment]
FYI there are:
- [hook2xmpp](dev.sum7.eu/genofire/hook2xmpp) based on [mattn](github.com/mattn/go-xmpp)
- [logmania](https://dev.sum7.eu/genofire/logmania) - also really hacky based on [yaja](https://dev.sum7.eu/genofire/yaja/)
- [thrempp](https://dev.sum7.eu/genofire/thrempp) - based on this library ;)

**Comment by mremond** [comment]
The main advantage of extensions is that they are extensible by the developer. You can use the lib and use your custom namespace extension.

We could have a getter for extensions, a bit similar to your nil test, that could look like (peudo-code):

```go
	var muc MUC
	if ok := p.Get(&MUC); ok {
		// Handle MUC
	}
```

Anyway, I am still torn between simplicity of your approach and trying to build something that is a bit more complex but could handle more developers' needs ...

**Comment by genofire** [comment]
Sounds nice - i really do not like this code: [code snipped from thrempp](https://dev.sum7.eu/genofire/thrempp/blob/9cb98c6cbcf773e31bb86b698b35be604ae1db6e/component/threema/send.go#L33-57)

**Comment by mremond** [comment]
Ok thanks for feedback, I will try to prepare something as discussed during the week-end :)

**Comment by mremond** [comment]
Here is what the code looks like for Message extension: https://github.com/FluuxIO/go-xmpp/commit/4a4c4850d104d8ef2d1d70cba06d0d90e3179edd

I will now expand Presence to have []PresExtension and implement a similar Get method.

**Comment by mremond** [comment]
I now think that oob and MUC presence extension should be ok for your needs.
I created #68 to track the development of XHTML extension support on messages.

**Comment by mremond** [comment]
@genofire I have added basic HTML support. You should have everything to port your code hopefully.
Please, open new issue if you think we are still missing important features.

**Comment by genofire** [comment]
#69 is for MUC not HTML

**Comment by mremond** [comment]
Oups, sorry, it is #70

**Comment by genofire** [comment]
Supi - now i need time to migrate by Programms ;)

Thank you for developing and maintaining xmpp library, it is really useful

**Comment by mremond** [comment]
Thanks for your feedback and your help :)

And no rush / no pressure to upgrade your programs, I have plenty to do as well.
