### ISSUE TITLE
Crashed with nil on socket by sending client

### ISSUE THREAD

**Issue by genofire** [FluuxIO/go-xmpp#74]
The workaround PostConnect works nice.
But there should not be crashed, if connect is not already established.

https://github.com/FluuxIO/go-xmpp/blob/7a386ec8d04c376aecd99d4cc109e934693005f6/client.go#L181

**Comment by genofire** [comment]
Maybe use channels for message to send (and recv) ...

**Comment by genofire** [comment]
It does not happen on startup only - a daemon crashed 8 times in the night with a nil there:
```
Jun 26 08:21:33 apus logmania[11512]: fmt.Fprintf(0x0, 0x0, 0xc0003a7a40, 0x94, 0x0, 0x0, 0x0, 0xc0003f3990, 0xc0000a3938, 0x415175)
Jun 26 08:21:33 apus logmania[11512]:         /usr/lib/go/src/fmt/print.go:200 +0x77
Jun 26 08:21:33 apus logmania[11512]: gosrc.io/xmpp.(*Client).Send(0xc0001d8320, 0x9ce580, 0xc00057afc0, 0xc00057afc0, 0x1)
Jun 26 08:21:33 apus logmania[11512]:         /home/genofire/projects/src/gosrc.io/xmpp/client.go:181 +0x1fa
```

Where do you use `Session.In` and `Session.Out` is it possible to use them?

**Comment by mremond** [comment]
I used channel before and this makes the code more complex. One options would be to have a custom queue and send the packet later if they are messages. Probably IQ and presence, should not be resent. The send would return an error for iqs, presence and, if queue is full only, for messages.

**Comment by genofire** [comment]
jep, you need only to query Message, maybe design it that it will drop messages if query is full.
(If you do not handle something, somebody else need to write such thinks in his code)

---

But the man problem is, that it `client.Send` should not crash, it should return with an error like _xmpp connection not established_

**Comment by mremond** [comment]
Yes, sure, I will first prevent the crash, no problem.

**Comment by mremond** [comment]
The crash should be fixed. Please, let know if this is not the case.

Addition of the queue is a larger feature request. It is tracked on #77.

**Comment by genofire** [comment]
Still not solved:
```
Jun 28 08:15:27 apus hook2xmpp[25880]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 28 08:15:27 apus hook2xmpp[25880]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x775ec7]
Jun 28 08:15:27 apus hook2xmpp[25880]: goroutine 12 [running]:
Jun 28 08:15:27 apus hook2xmpp[25880]: gosrc.io/xmpp.(*Client).Send(0x0, 0xd180c0, 0xc00012f680, 0xc00012f680, 0x1)
Jun 28 08:15:27 apus hook2xmpp[25880]:         /home/genofire/projects/src/gosrc.io/xmpp/client.go:159 +0x37
```

**Comment by mremond** [comment]
ok, thanks. Let's reopen it. I will try to reproduce it on my own client to fix it for good.

**Comment by mremond** [comment]
I am not sure how you are using it. Error on line 159 implies that the Client would be nil inside its own receiver ?
Are you passing the client to several go routines ?

**Comment by mremond** [comment]
Do you have in your trace which call to client.Send is crashing ?
For example here, you are refering to a global variable `client`: https://dev.sum7.eu/genofire/hook2xmpp/blob/2435b9b73b366fa07c10a164a0c126b55192fd03/xmpp.go#L20

**Comment by mremond** [comment]
It seems that those reference to client in xmpp.go are indeed triggered through postStartup method.
They are referring to a global client pointer, but it is never set anywhere.
Here, you are using operator := so your should be creating a local client variable:
https://dev.sum7.eu/genofire/hook2xmpp/blob/2435b9b73b366fa07c10a164a0c126b55192fd03/main.go#L36

Could it be that the crash is triggered because you are calling client.Send on a nil pointer ?
This is just an alias for Send(*Client, ...) so it would explain the crash when using client.conn.
However, a method receiver is not supposed to check for nil pointer on its own receiver.

**Comment by genofire** [comment]
sorry for this late answer - look like it works (in hook2xmpp) -> need to check it again in logmania ;)

**Comment by genofire** [comment]
okay hook2xmpp runs now for 1d and 10h without panic.
I think i found also the problems logmania.

I thought it was just my foul - looking on own code with some time going helps
