### ISSUE TITLE
Add ability to send an IQ and pass a callback that will get triggered by reply

### ISSUE THREAD

**Issue by mremond** [FluuxIO/go-xmpp#78]

**Comment by wichert** [comment]
Perhaps the way to do this is to add a one-shot route option? That way you can do something like this:

```go
router.NewRoute().OneShot().AddMatcher(IqResult("id")).HandlerFunc(…)
```

A downside of this approach is this API forces the Router to use a single slice for permanent and one-shot routes, and it might be a little expensive to remove one-shot entries from the list frequently.

A more efficient approach might be to use a separate simple data structure for one-shot routes. Maybe just a map from id to handler function? The API could then look like this:

```go
router.NewOneShotRoute("1371").HandlerFunc(….)
```

I'm not entirely sure what the requirements for id uniqueness are - perhaps this needs to key on a (bare?) jid and id pair?
